// **********************************************************************
// Parsed By TarsParser(1.1.0), Generated By tars2node(20190529)
// TarsParser Maintained By <TARS> and tars2node Maintained By <superzheng>
// Generated from "node.tars" by Imp Mode
// **********************************************************************

"use strict";

var Demo = require("./node.js").Demo;
module.exports.Demo = Demo;

Demo.HelloImp.prototype.initialize = function () {
    //TODO::
};

Demo.HelloImp.prototype.ping = function (current) {
    current.sendResponse("pong");
};