// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.qq.tars.quickstart.server.demo;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface HelloPrx {

	public String ping();

	public String ping(@TarsContext java.util.Map<String, String> ctx);

	public void async_ping(@TarsCallback HelloPrxCallback callback);

	public void async_ping(@TarsCallback HelloPrxCallback callback, @TarsContext java.util.Map<String, String> ctx);
}
