name: framework-nightly-test

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: test framework nightly build
        run: |
          ./autorun.sh nightly latest false